### PR TITLE
Feature: Preserve "from" year

### PR DESCRIPTION
**Pull request by aschepler**
I've modified the behavior of `<<yeartoyear>>` so that a `*` character at the start of the first argument requests to leave the "From Date" year alone when updating an existing header. This is useful for an older project that has migrated source control, operating system, etc. so that the file creation timestamp doesn't always reflect the true age of the file contents.

I'm quite new to TypeScript, so all improvements, suggestions, and other notes in the review will be appreciated.

### CODE REVIEW

**Comment by davidquinn** [comment]
Thanks for the heads up. Actually, most of the code here is not required as it looks like a simple bug fix. I will make the fix and upload a new version tomorrow. I will then come back and close this.

Regards
David

**Comment by aschepler** [comment]
This isn't a fix for the issue I opened - it's a separate proposed new functionality.

**Comment by davidquinn** [comment]
My bad (it's late!) - I'll take a look at it tomorrow.

**Comment by davidquinn** [comment]
Sorry, not ignoring this. Have been ill, feedback hopefully tomorrow but generally looks like right solution with just a few tweaks.

**Comment by aschepler** [comment]
There's no hurry for me. Hope you feel well soon.

**Comment by davidquinn** [comment]
Thanks for this Andrew - I think this basically works as an approach. 

Some of my are just there more because you said you are new to typescript.

As you may have picked up from the repository, I have been maintaining this for a number of years but have only recently put it up on GitHub. Some of the comments below belie the fact that I have not added any coding standards to the repository as yet, so I will rectify that soon.

* [MEDIUM] I am not convinced that we need a special “static” character (“*”) that could be applied to *_any_* option because there are only two possible argument values that are not already static that *_could_* be affected by this: `fc` and `now`. So it might be as easy (and make the code more readable) to just have 2 more standard argument values. Although for naming the two new values, we already have a concept of suffixing variables with either `!U` or `!L` to force case, so I am wondering if we follow that convention and suffix `fc` and `now` with (say) `!S` or even just `!` and deal with them specifically in `y2yYear` by turning the current if…else… into a switch statement that deals with each of the (now 4) specific options. The switch would have the added benefit of only calling lowercase on the arg once.
* [LOW] In typescript, `null` is `false` so instead of `let a = b !== null ? b : c;` you can just write `let a = b ?? c;` (e.g. helper.ts line 788).
* [HIGH] I would prefer that we apply the same logic to both the from and to dates. I realise that your use case is the more likely scenario where the from year remains static, but I am 98% convinced that someone will come up with a reason why they need to keep the second one static (end of the world, maybe?). For this, abstract out the logic that determines the value into its own function and then call that to calculate each of from and to years.
* [LOW] I prefer the term “previous” to “old”, but that may just be me.
* [MEDIUM] Wherever you refer to the previous value, unless there is a reason to do so that I haven’t picked up on, I would prefer to use `null` rather than en empty string. For me `null` means `null`, and with the point earlier about `null` is `false` I think it makes typescript code easier to read.
* [MEDIUM] I have noticed a bug in the original code (not your code) - the `y2yYear` function does not seem to take account of the `var:name` option mentioned in the readme.md. I will take a closer look at that but as it is in exactly the same area that you have been looking at I will leave it until we get this sorted. I will raise a bug for that.

BTW, thanks for fixing some of the typos in the readme - I have been meaning to go through that for a while.

Regards
David

**Comment by aschepler** [comment]
One additional point: the regexp parsing to identify previous text can
become fragile if the line contains multiple variables/functions without
much between them. If for some reason a template has "Text <<author>>
<<yeartoyear>>", we get the regexp /Text .+? /, so if the previous author
string contains a space, it will end up looking for the "from year" at the
start of the author's last name or whatever, and fail. I think the logic
could be improved in some ways (add /(?=\d)/ at the end!) but there is no
fully general solution.

On Sat, May 22, 2021 at 5:17 AM dq ***@***.***> wrote:

> Thanks for this Andrew - I think this basically works as an approach.
>
> Some of my are just there more because you said you are new to typescript.
>
> As you may have picked up from the repository, I have been maintaining
> this for a number of years but have only recently put it up on GitHub. Some
> of the comments below belie the fact that I have not added any coding
> standards to the repository as yet, so I will rectify that soon.
>
>    - [MEDIUM] I am not convinced that we need a special “static”
>    character (“*”) that could be applied to *any* option because there
>    are only two possible argument values that are not already static that
>    *could* be affected by this: fc and now. So it might be as easy (and
>    make the code more readable) to just have 2 more standard argument values.
>    Although for naming the two new values, we already have a concept of
>    suffixing variables with either !U or !L to force case, so I am
>    wondering if we follow that convention and suffix fc and now with
>    (say) !S or even just ! and deal with them specifically in y2yYear by
>    turning the current if…else… into a switch statement that deals with each
>    of the (now 4) specific options. The switch would have the added benefit of
>    only calling lowercase on the arg once.
>
> Got it.

Though another generalization I thought of but didn't want to take on as
part of this change: what if every <<variable/function>> can specify
whether to replace or reuse previous text? Since there's already means of
controlling which lines are replaced or kept, this would mostly make sense
if a template has a <<>> which should replace previous text and a <<>>
which should reuse previous text in the same line. A variable value won't
change from just one file save to the next, but after the config gets
changed or if there are multiple users with different variable settings
configured, this might be wanted. The !S syntax could make sense for these
too, like <<extraVar!S>> or <<company!US>>. Parsing the previous line would
get even trickier, though. Anyway, I don't see obvious use cases calling
for this, but I guess the idea can stay as a potential future change, with
maybe better ways to go about it.


>    - [LOW] In typescript, null is false so instead of let a = b !== null
>    ? b : c; you can just write let a = b ?? c; (e.g. helper.ts line 788).
>
> Oh good. I wondered there if there was an appropriate JS/TS operator to
shorten that, but forgot about it before following up.

>
>    - [HIGH] I would prefer that we apply the same logic to both the from
>    and to dates. I realise that your use case is the more likely scenario
>    where the from year remains static, but I am 98% convinced that someone
>    will come up with a reason why they need to keep the second one static (end
>    of the world, maybe?). For this, abstract out the logic that determines the
>    value into its own function and then call that to calculate each of from
>    and to years.
>
> Sure. Seems unlikely, but that's exactly when users surprise designers.

>
>    - [LOW] I prefer the term “previous” to “old”, but that may just be me.
>
> I think I wanted to avoid any confusion with "previous" as in "the line
just above this one in the file/template". But maybe that's not a big
concern when seen in context.

>
>    - [MEDIUM] Wherever you refer to the previous value, unless there is a
>    reason to do so that I haven’t picked up on, I would prefer to use null
>    rather than en empty string. For me null means null, and with the
>    point earlier about null is false I think it makes typescript code
>    easier to read.
>
> It might have simplified some checks on the variable as in using
''.substr(a,b) which is valid and results in another empty string. But yes,
null is more obvious.

>
>    - [MEDIUM] I have noticed a bug in the original code (not your code) -
>    the y2yYear function does not seem to take account of the var:name
>    option mentioned in the readme.md. I will take a closer look at that but as
>    it is in exactly the same area that you have been looking at I will leave
>    it until we get this sorted. I will raise a bug for that.
>
> BTW, thanks for fixing some of the typos in the readme - I have been
> meaning to go through that for a while.
>
I just edited the things I happened to see, since I had other content
changes in the same file.

**Comment by davidquinn** [comment]
I take your point about the regex for identifying the current value and I think you are correct. This might need a bit more thought before committing to a change. Maybe we need to only guarantee that this will work for year as a number so we have a chance to confirm that the selected value is actually a four digit year.

re: generalising this to all variables, I agree that this should be considered separately because it is likely to be much less common and adds a level of complexity way beyond what doing this for a year value alone brings.

If you are comfortable with where we are with the comments, I am happy for you to make the requisite changes and do some testing before merging.

Regards
D

**Comment by davidquinn** [comment]
Hi Andrew, 

This hasn't had any action for a while so just checking in that you are still keen on it. I will be doing some work on the extension soon, so I can make the changes discussed above and incorporate this as well.

Let me know if you have any thoughts from my last message.

**Comment by aschepler** [comment]
This has been on my list still, but I haven't made progress. I wouldn't
mind at all if you take it over.

The function calls would probably need to work a bit differently to get the
regular expression to include the expected existing content of exactly 4
digits in a row. But I think adding something like that should solve all
but the most pathological cases of issues with consecutive variable
expansions.

Thanks,
Andrew

**Comment by simon-abbott** [comment]
Any progress on this? I'm looking at using this extension for a project of mine and the years are way off due to git not tracking timestamp metadata, so this is a must-have for me.

**Comment by davidquinn** [comment]
There is a lot to go through in here. I have other stuff on that I will be finished with just before Christmas, so I will go through this over the Christmas/New Year period.

**Comment by davidquinn** [comment]
I think we are close to committing this. I have just done some minor tweaks to replace a couple of deprecated function calls and testing so far looks good. I will package up, bump version and merge into main soon.

Thanks for the work on this Andrew.

Regards
David

**Pull request merged**
