### PR TITLE
Add ability to use workspace folder as root dir

### PR DESCRIPTION
**Pull request by thirstyice**
If `rootDirFileName` is defined as an empty string, get the root directory by looking at the workspace folders instead.

See discussion in #78

### CODE REVIEW

**Review by davidquinn — CHANGES_REQUESTED** [review]
Thanks for submitting this PR. However there are a couple of problems with this change that need to be addressed before it can be approved.

As noted in [the original issue](https://github.com/davidquinn/psi-header/issues/78), the `rootDirFileName` setting has only been required since Microsoft introduced the concept of multiple workspaces in VSCode - prior to this, the extension worked pretty much how you would like it to work. But now it is more complicated because you can now be working with potentially zero, one or multiple root workspaces - and it can depend on how you opened the file to edit it. 

A secondary enhancement request that led to the current logic was that users wanted the ability to define the root path of an edited file to be relative to the file rather than always assuming a fixed root path for all files in a ‘project’. 

Therefore, the solution to the above issues was to look at the physical path of the file in the editor and base the root path on a specific known file that was closest in the folder hierarchy to the edited file. This solved #2 and also made the extension work regardless of workspaces.

`rootDirFileName` and the associated logic were introduced specifically to solve the above problems. However, in order to not break the functionality for existing users, this setting is optional and falls back to `package.json`. Anecdotally, I know that a lot of users currently use this fallback.

As a result of the above, this PR introduces the following problems for existing users:
* The new implementation assumes that the extension will use the workspace folders if the user has not specifically set a `rootDirFileName` in their config. This will be a breaking change as mentioned above.
* The new implementation also assumes that by default the root for the project is always the workspace root for all files.

I think all of the above can be solved by adding another config option that allows a user to opt in to using workspaces to determine the root directory and adding a check for that in the `if` statement on the new line 404.

Once that is done, you will need to test what happens if the user edits a file that was opened  (a) directly and not via a workspace, (b) via a single workspace, (c) via a multi-workspace ‘project’ and (d) where a specific `rootDirFileName` is set.

**Comment by thirstyice** [comment]
Here's the current behaviour. Which bit do you have an objection to?

| **Condition** | **Old Behaviour** | **New Behaviour** |
| --- | --- | --- |
| File w/ no workspace (default) | Root folder is first parent folder w/ `package.json`. If no `package.json`, root folder is `.`| Same as Old Behaviour |
| File in a single workspace folder, workspace has only one folder (default) | Same as above | Same as Old Behaviour |
| File in a single workspace folder, workspace has multiple folders (default) | Same as above | Same as Old Behaviour |
| File in multiple nested workspace folders (default) | Same as above | Same as Old Behaviour |
| **Condition** | **Old Behaviour** | **New Behaviour** |
| File w/ no workspace (`rootDirFileName == "xxx"`) | Root folder is first parent folder w/ `xxx`. If no `xxx`, root folder is `.`| Same as Old Behaviour |
| File in a single workspace folder, workspace has only one folder (`rootDirFileName == "xxx"`) | Same as above | Same as Old Behaviour |
| File in a single workspace folder, workspace has multiple folders (`rootDirFileName == "xxx"`) | Same as above | Same as Old Behaviour |
| File in multiple nested workspace folders (`rootDirFileName == "xxx"`) | Same as above | Same as Old Behaviour |
| **Condition** | **Old Behaviour** | **New Behaviour** |
| File w/ no workspace (`rootDirFileName == ""`) | Root folder is first parent folder w/ `package.json`. If no `package.json`, root folder is `.`| Same as Old Behaviour |
| File in a single workspace folder, workspace has only one folder (`rootDirFileName == ""`) | Same as above | Root folder is workspace folder |
| File in a single workspace folder, workspace has multiple folders (`rootDirFileName == ""`) | Same as above | Root folder is whichever workspace folder contains File |
| File in multiple nested workspace folders (`rootDirFileName == ""`) | Same as above | Root folder is whichever workspace folder containing File is listed first (making this smarter would increase processing time) |

**Comment by davidquinn** [comment]
My main objection is that the PR changes the meaning of `rootDirFileName` where it is null or empty in a way that will break expected current behaviour for a large number of existing users. See my comments in the additional column below, but to understand them you need to understand the following:
* the current behaviour is that the code will default `rootDirFileName` to `package.json` if it is null or empty. In the PR this will only happen if there are no workspace folders as it occurs within the `else` block which is after the PR has already decided to use the workspace root.
* Opening a folder in VSCode automatically creates a workspace pointing to that folder. This effectively means that there is nearly always at least one workspace folder in normal usage. Again, this means that the intended default value for `rootDirFileName` will never be set leading to a breaking change.

The above is highly likely to impact a large number of users.

| **Condition** | **Old Behaviour** | **New Behaviour** | **New Behaviour Comment** |
| --- | --- | --- | --- |
| File w/ no workspace (default) | Root folder is first parent folder w/ \`package.json\`. If no \`package.json\`, root folder is \`.\` | Same as Old Behaviour | Correct |
| File in a single workspace folder, workspace has only one folder (default) | Same as above | Same as Old Behaviour | Incorrect. It is the same behaviour if and only if `rootDirFileName` is specifically defined in the config, otherwise this is a breaking change that ignores the current default value for `rootDirFileName`. |
| File in a single workspace folder, workspace has multiple folders (default) | Same as above | Same as Old Behaviour | Incorrect - see above |
| File in multiple nested workspace folders (default) | Same as above | Same as Old Behaviour | Incorrect - see above |
| **Condition** | **Old Behaviour** | **New Behaviour** | **New Behaviour Comment** |
| File w/ no workspace (\`rootDirFileName == "xxx"\`) | Root folder is first parent folder w/ \`xxx\`. If no \`xxx\`, root folder is \`.\` | Same as Old Behaviour | Correct |
| File in a single workspace folder, workspace has only one folder (\`rootDirFileName == "xxx"\`) | Same as above | Same as Old Behaviour | Correct |
| File in a single workspace folder, workspace has multiple folders (\`rootDirFileName == "xxx"\`) | Same as above | Same as Old Behaviour | Correct |
| File in multiple nested workspace folders (\`rootDirFileName == "xxx"\`) | Same as above | Same as Old Behaviour | Correct |
| **Condition** | **Old Behaviour** | **New Behaviour** | **New Behaviour Comment** |
| File w/ no workspace (\`rootDirFileName == ""\`) | Root folder is first parent folder w/ \`package.json\`. If no \`package.json\`, root folder is \`.\` | Same as Old Behaviour | Correct |
| File in a single workspace folder, workspace has only one folder (\`rootDirFileName == ""\`) | Same as above | Root folder is workspace folder | This is a breaking change as it ignores the current meaning of `rootDirFileName` is null or empty. |
| File in a single workspace folder, workspace has multiple folders (\`rootDirFileName == ""\`) | Same as above | Root folder is whichever workspace folder contains File | See above comment. |
| File in multiple nested workspace folders (\`rootDirFileName == ""\`) | Same as above | Root folder is whichever workspace folder containing File is listed first (making this smarter would increase processing time) | See above comment. |

As I said in the previous message, rather than hijack the purpose of `rootDirFileName == ""`, your desired behaviour could be achieved without breaking the current behaviour by adding an additional config setting. For example, a boolean setting `rootDirPreferWorkspace` that allows a user to opt into the new behaviour. This would then be included in the `if` statement on line 404 of the PR.

**Comment by thirstyice** [comment]
What system are you on where you're seeing that the default behaviour is changed?

**Comment by davidquinn** [comment]
Actually, I was wrong - I misread the if statement and confused rootDirFileName 'is null' with 'is falsy'.

Could you please update the documentation in README.md to reflect the change of behaviour for rootDirFileName.

I will handle updating CHANGELOG.md and merge your code into another update I am currently working on. I should be able to test and release it over the weekend.

**Comment by thirstyice** [comment]
Fair enough. You had me worried that the way defaults are handled might be different across platforms lol.

Readme has been updated.
Let me know if you need anything further to merge.

**Pull request merged**
